# Travis CI configuration file
# http://about.travis-ci.org/docs/

language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"

env:
  - TWISTED=latest SQLALCHEMY=latest SQLALCHEMY_MIGRATE=latest

# Dependencies installation commands
install:
  # zope.interface dropped Python 2.5 support in 4.0.0
  - "[ $TRAVIS_PYTHON_VERSION != '2.5' ] || pip install 'zope.interface<4.0.0'"
  - "[ $TWISTED = latest ] || pip install Twisted==$TWISTED"
  - "[ $SQLALCHEMY = latest ] || pip install sqlalchemy==$SQLALCHEMY"
  - "[ $SQLALCHEMY_MIGRATE = latest ] || pip install sqlalchemy-migrate==$SQLALCHEMY_MIGRATE"
  - pushd master; python setup.py develop; popd
  - pushd slave;  python setup.py develop; popd
  # mock is preinstalled on Travis
  # txgithub requires Twisted >= 12.3.0, which doesn't work on Python 2.5.
  - "[ $TRAVIS_PYTHON_VERSION = '2.5' ] || pip install txgithub"

# Tests running commands
script:
  - TZ=Europe/Moscow trial buildbot.test
  - TZ=Europe/Moscow trial buildslave.test

notifications:
  email: false
